export const GET_THEATER_SYSTEM_REQUEST = "theater/GET_THEATER_SYSTEM_REQUEST";
export const GET_THEATER_SYSTEM_SUCCESS = "theater/GET_THEATER_SYSTEM_SUCCESS";
export const GET_THEATER_SYSTEM_FAILED = "theater/GET_THEATER_SYSTEM_FAILED";
