export const GET_THEATER_CLUSTER_REQUEST =
  "theater/GET_THEATER_CLUSTER_REQUEST";
export const GET_THEATER_CLUSTER_SUCCESS =
  "theater/GET_THEATER_CLUSTER_SUCCESS";
export const GET_THEATER_CLUSTER_FAILED = "theater/GET_THEATER_CLUSTER_FAILED";
